# Generated by Django 3.2.5 on 2021-07-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Ages',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='SOMECATEGORY', on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(default='White', on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='product.age'),
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='product.country'),
        ),
    ]
