# Generated by Django 3.2.5 on 2021-07-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_item_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.country'),
        ),
    ]
