# Generated by Django 3.2.5 on 2021-07-18 16:47

from django.db import migrations, models
import django.db.models.deletion
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_item_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.age'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.country'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title'),
        ),
    ]
