# Generated by Django 3.2.5 on 2021-07-19 17:18

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=slugger.fields.AutoSlugField(default='0', populate_from='category'),
        ),
    ]
