# Generated by Django 3.2.5 on 2021-07-19 17:19

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=slugger.fields.AutoSlugField(default='', populate_from='category'),
        ),
    ]
