# Generated by Django 3.2.5 on 2021-07-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.material'),
        ),
    ]
