# Generated by Django 3.2.5 on 2021-07-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_item_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='guarantee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.guarantee'),
        ),
    ]
