# Generated by Django 3.2.5 on 2021-07-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_item_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='guarantee',
        ),
    ]
